### ISSUE TITLE
parsing new MSFragger result tables

### ISSUE THREAD

**Issue by hayse1** [wenbostar/PDV#10]
Hi Bo, we are making some changes to the formatting of the MSFragger psm.tsv result files from FragPipe/Philosopher, and our updated tables are no longer compatible with PDV. Can you take a look at this new table?

Thank you!
Sarah
[psm.tsv.zip](https://github.com/wenbostar/PDV/files/3785602/psm.tsv.zip)

**Comment by wenbostar** [comment]
Hi Sarah,
Could you please tell us what the change is compared with the last version? PDV only requires the six columns listed here for MSFragger psm.tsv: https://github.com/wenbostar/PDV/wiki/MSFragger-pipeline. If none of the six columns is changed, it should work well.
Bo

**Comment by hayse1** [comment]
Unfortunately we can't load the new tables.
![image (3)](https://user-images.githubusercontent.com/16582242/67961838-a4513480-fbd2-11e9-8619-e86e8350035b.png)
![image (4)](https://user-images.githubusercontent.com/16582242/67961849-a74c2500-fbd2-11e9-8f09-7d56ef31f349.png)

We've added a few columns and the order may have changed, but the 6 columns should still have the same names. A new table is attached to my first message, let me know if I can send you anything else. Thanks again!

Sarah

**Comment by KaiLiCn** [comment]
Hi Sarah,
Can you share the spectrum file you used with us?
Kai

**Comment by hayse1** [comment]
Hi Kai, [here's](https://umich.box.com/s/lfsqvwllz2hexv9ubkwfqar0zj6ppcho) a link to the psm report and the mzML file. Thank you!

**Comment by KaiLiCn** [comment]
By the way, for the column _Observed   Modifications_, I didn't include these modifications as there is no position information. Should I consider them as additional modifications?

**Comment by hayse1** [comment]
That might be good. In this case the 'Observed Modifications' are not very informative since they're just the mass shifts from the isotope error allowed in the search (+1/+2) that are being mapped to Unimod. But in the case of an open search, the different comma-separated possibilities for the observed mass shift for a PSM are more meaningful. Thanks so much!

**Comment by fcyu** [comment]
@KaiLiCn Thanks for your efforts. `Observed Modifications` are inferred from delta mass, so there is no localization info in the `psm.tsv`. I don't think there is a way to confidently localize all `Observed Modifications`. Thus, I suggest don't include `Observed MOdifications` in spectral annotation, which may introduce misleading results. BTW, your [document](https://github.com/wenbostar/PDV/wiki/MSFragger-pipeline) shows that PDV doesn't use `Observed Modification` column.

Thanks,

Fengchao

**Comment by KaiLiCn** [comment]
@fcyu Thanks for your reply. PDV doesn't include `Observed MOdifications` now.
@hayse1 Sarah, we fixed the bug and updated PDV to 1.5.4. It should work now.

**Comment by hayse1** [comment]
Looks great, thanks so much! We use PDV a lot so this is very helpful :)

Thanks again,
Sarah
