### ISSUE TITLE
not see the spectrum image

### ISSUE THREAD

**Issue by fazeliniah** [wenbostar/PDV#11]
Hi, 
I am using the newest version of PDV to visualize MSFragger output (through fragpipe) on our Windows10 desktop. I used the pep.xml and mzML files according to the manual. The files seem to be parsed by PDV but it doesn't generate the annotated spectrum.  Please see he attached file. Any help will be greatly appreciated. 
Thanks
![PDV_issue](https://user-images.githubusercontent.com/19155957/87593634-bff56000-c6b9-11ea-93b2-a6de7f1781d7.PNG)

**Comment by KaiLiCn** [comment]
Sorry for the inconvenience. Could you please share the log file with us? It should be in PDV package folder named logs/PDV.log. And if you can share this pep.xml and mzML, I will fix it more quickly.

Kai

**Comment by fazeliniah** [comment]
I have uploaded the files in my dropbox. Please find them in this link: 
https://www.dropbox.com/sh/t18cfwqpw17bzqi/AABPPi51LXHOp4GZRMyw-MbEa?dl=0

**Comment by KaiLiCn** [comment]
Hi,

I just tested the files you shared with me. However, PDV ran well on them (on Windows 10 and Mac). 
![image](https://user-images.githubusercontent.com/29800230/87607308-aa386880-c6c2-11ea-8d1e-91267cfedb2a.png)
I noticed the pep.xml file you used was different. Could you please check your input files? I will add more exception captures in next version. Please let me know if it still has problem.

Kai

**Comment by fazeliniah** [comment]
Hi Kai, 
That's very strange. I used the same exact files on my win10 machine and still get the blank frame for the spectrum image. I have generated a new PDV log file. I am not sure why it is not working properly for me. 
Thanks
[PDV.log](https://github.com/wenbostar/PDV/files/4932522/PDV.log)

**Comment by KaiLiCn** [comment]
Don't worry. I will generate a debug version package for you, maybe later today or tomorrow. And I will output some messages into log file to see what's wrong with it.

Kai

**Comment by KaiLiCn** [comment]
Did you notice the input pep.xml you used was different with what you sent to me?
![image](https://user-images.githubusercontent.com/29800230/87746859-40e65180-c7b7-11ea-9f8d-bccec3565420.png)
![image](https://user-images.githubusercontent.com/29800230/87746894-578ca880-c7b7-11ea-9342-047c3ab4a29f.png)
I think the file you input may have some problem. Could you share the same one with me?

I also generated a debug version, please download from Google Drive: [PDV-1.6.0.debug](https://drive.google.com/file/d/19mFFxsbl62EeDgLeVBcwcaV-3rShFrhY/view?usp=sharing)
You will get similar info in log file:
![image](https://user-images.githubusercontent.com/29800230/87747884-15b13180-c7ba-11ea-8b1e-12a28fc6565a.png)

Kai

**Comment by fazeliniah** [comment]
I didn't get any error with MSFragger (just couple of warnings). 
Please find the file that you requested in this link: https://www.dropbox.com/s/kui6h71gs4lbsjx/interact-q200707_helaa_dda_01.pep.xml?dl=0
Thanks

**Comment by KaiLiCn** [comment]
That's so wired. I downloaded the latest PDV-1.6.0 from Github and input the new files you just sent to me. There was no error... I tried it on three different Windows computers.
![image](https://user-images.githubusercontent.com/29800230/87804414-76238b80-c819-11ea-8687-05c12fb444cd.png)
Sorry for the inconvenience. Could you please download PDV-1.6.0 and try it again? Please let me know if it still doesn't work.

Kai

**Comment by wenbostar** [comment]
@fazeliniah , what is the java version in your system?

**Comment by fazeliniah** [comment]
I downloaded the PDV again on the same computer and the problem persists. I will try it on different desktops and let you know how it goes. 
The Java is version 8 (update 261). 
Thanks for your help.

**Comment by fazeliniah** [comment]
I tested PDV-1.6.0 with the same files on my Macbook and it is working beautifully and I can see the spectrum. Still not sure, why my Win10 desktop is failing to do so.

**Comment by wenbostar** [comment]
> I downloaded the PDV again on the same computer and the problem persists. I will try it on different desktops and let you know how it goes.
> The Java is version 8 (update 261).
> Thanks for your help.

Java 8 is fine.

**Comment by wenbostar** [comment]
We just released a new version in which we fixed a few bugs. Please reopen this issue if you still encounter the same problem using the new version.
