### ISSUE TITLE
Column selection not working

### ISSUE THREAD

**Issue by Alemarcohen** [wenbostar/PDV#13]
Interesting: Yesterday I downloaded PDV to view data generated in Fragpipe, and it worked nicely.  I was able to open the View>Column Selection. and added the proteinID and descriptions (these are really good for users of our proteomics core facility to browse and filter their data).

Today, I cant get Column Selection to open in both of my computers where I downloaded PDV. When I click ColumnSelection, an empty  window appear where I can only read: "Column"

Any ideas?

![Screenshot 2020-11-17 120026](https://user-images.githubusercontent.com/29800323/99413802-871a0180-28cc-11eb-9f40-fb21cb3dc735.gif)

**Comment by KaiLiCn** [comment]
Sorry for the inconvenience. Could you please share your input files, including .pepXML and .mzML with us? I will take a look and fix it today.

**Comment by Alemarcohen** [comment]
You can close this ticket. My mistake, I had not opened the appropriate
files.

Alex

**Comment by KaiLiCn** [comment]
No problem. Feel free to ask us if you need any help.
