### ISSUE TITLE
column selection not work

### ISSUE THREAD

**Issue by freeedog** [wenbostar/PDV#15]
Viewing MaxQuant result
![image](https://user-images.githubusercontent.com/33932424/105293769-2670b300-5bf4-11eb-8bd4-7a7f34d4bfc8.png)

**Comment by KaiLiCn** [comment]
Hi,

Sorry for the inconvenience. I also noticed there is a bug. I am working on it and will release a new version in few days.

Kai

**Comment by KaiLiCn** [comment]
Hi,

The bug was fixed (PDV.1.7.1). Please let me know if you find any problems.

Kai
