### ISSUE TITLE
mvn package failed

### ISSUE THREAD

**Issue by achucode** [wenbostar/PDV#17]
Dear all,

Would be glad of any help or pointer. I downloaded PDV-1.7.1 and, seeing a pom.xml, decided to install the package by having, as I do normally, maven do the work by issuing

> mvn package

I'm getting however Build failures, copied below:
--------------------------------------------
INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  04:21 min
[INFO] Finished at: 2021-02-03T14:52:22+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project PDV: Could not resolve dependencies for project PDV:PDV:jar:1.7.1: Failed to collect dependencies at uk.ac.ebi.pride.jaxb:pride-jaxb:jar:1.0.9 -> psidev.psi.tools:xxindex:jar:0.12 -> org.apache.commons:com.springsource.org.apache.commons.io:jar:1.4.0: Failed to read artifact descriptor for org.apache.commons:com.springsource.org.apache.commons.io:jar:1.4.0: Could not transfer artifact org.apache.commons:com.springsource.org.apache.commons.io:pom:1.4.0 from/to intact.nexus (http://www.ebi.ac.uk/intact/maven/nexus/content/groups/public/): Failed to transfer file: http://www.ebi.ac.uk/intact/maven/nexus/content/groups/public/org/apache/commons/com.springsource.org.apache.commons.io/1.4.0/com.springsource.org.apache.commons.io-1.4.0.pom. Return code is: 500 , ReasonPhrase:Internal Server Error. -> [Help 1]
-----------
I find that indeed  

http://www.ebi.ac.uk/intact/maven/nexus/content/groups/public/org/apache/commons/com.springsource.org.apache.commons.io/1.4.0/com.springsource.org.apache.commons.io-1.4.0.pom

does not exist.

Any idea how to fix the problem? Many thanks in advance,

Achu

**Comment by KaiLiCn** [comment]
Hi Achu,

I am not very sure what's the exact reason for this problem. It might be the maven environment issue.

I met this similar problem before and here is one of the potential solutions. 1. Locate the maven repository folder for this package on your PC  and delete it (Windows: C:\Users\YourName\.m2\repository\uk\ac\ebi\pride\jaxb\pride-jaxb\1.0.9); 2. Reload PDV in your IDE. It might work.

Kai

**Comment by achucode** [comment]
Dear Kai,

Thank you Kai. I'm on Linux so I slightly adjusted the path. I'm afraid however that this solution did not work for me, I get the same error again.

How are you guys compiling this package normally? Via intellij?

Best wishes,
Achu

**Comment by KaiLiCn** [comment]
Yes, we manage and compile the project via IntelliJ IDEA on Windows or Mac. Maybe you could check the path under your home folder: ~/.m2/repository/...
