### ISSUE TITLE
It is wrong when I import my mascot result (xxx.dat) 

### ISSUE THREAD

**Issue by ningzaizai** [wenbostar/PDV#20]
dear guy, I am bothered about you, but I have a problem when I imported my Mascot result (.dat), please look at bellow picture.
could you help me when you are convenient? Thanyou！

![image](https://user-images.githubusercontent.com/81786796/113372530-7a89d780-939b-11eb-845d-7b6cafb2f1ed.png)
![image](https://user-images.githubusercontent.com/81786796/113372722-e409e600-939b-11eb-95ae-656438aaf333.png)

**Comment by wenbostar** [comment]
Could you share with us the dat file for debugging?

**Comment by ningzaizai** [comment]
OK！the attachment is my dat file.

**Comment by wenbostar** [comment]
I don't find the link for the file.

**Comment by ningzaizai** [comment]
sorry, it don't support file type when I upload the dat file

**Comment by wenbostar** [comment]
How big is the file?

**Comment by ningzaizai** [comment]
it is 861M, and I compress it to dat.7z ，but it still don't upload

**Comment by ningzaizai** [comment]
I have upload the dat file to pan.baidu, you can try to download.
link：https://pan.baidu.com/s/1wiaxorJdfEJKXXQrI9j3uA 
password：pf3s

**Comment by ningzaizai** [comment]
I sincerely hope you can deal with the problem, and I am waiting for the result to report my boss. Thank you so much!

**Comment by KaiLiCn** [comment]
Hi there,

I will take a look and hopefully give you feedback early next week.

Kai

**Comment by KaiLiCn** [comment]
Hi, I fixed this problem and will release the PDV 1.7.2 tomorrow(4/5 US).

**Comment by wenbostar** [comment]
@ningzaizai , the new version 1.7.2 (https://github.com/wenbostar/PDV/releases/tag/v1.7.2) is now available. Please give it a try and let us know if it works.

**Comment by ningzaizai** [comment]
Now ,it is ok to load the dat file by the the new version 1.7.2 . Thankyou very much!

**Comment by wenbostar** [comment]
Great. Feel free to let us know if you have any questions about PDV in the future.

**Comment by ningzaizai** [comment]
ok.
