### ISSUE TITLE
How to open the files produced by MSFragger?

### ISSUE THREAD

**Issue by ZhangXiangye** [wenbostar/PDV#24]
Hello,

We are running the PDV-1.7.3 to open the files produced by MSFragger.
But we can only open the file called "psm.tsv". However, the data we need was stored in the "global.modsummary.tsv" or "modifications.tsv". Could you please tell me if the PDV could open such files? 

Thank you in advance.

ZXY.

**Comment by KaiLiCn** [comment]
Hi,

Sorry, PDV now only supports the "psm.tsv" file as the input. If you want to know more detail about your search result, you can find the *.pep.xml result file exported by MSFragger. PDV supports the *.pep.xml file as the input file.

Kai

**Comment by ZhangXiangye** [comment]
Hi Kai,


Thanks for your reply, I’ve find&nbsp;the *.pep.xml as you suggested, and it works!&nbsp;


Have a great day!


ZXY

发自我的iPhone


------------------ Original ------------------
From: KaiLiCn ***@***.***&gt;
Date: Sun,Jun 13,2021 0:33 PM
To: wenbostar/PDV ***@***.***&gt;
Cc: Shane ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [wenbostar/PDV] How to open the files produced by MSFragger? (#24)

**Comment by KaiLiCn** [comment]
Great! Please feel free to start a new issue if you meet any new problem.

Kai
