### ISSUE TITLE
PDV Gui 

### ISSUE THREAD

**Issue by kbackus4** [wenbostar/PDV#26]
I just downloaded PDV (trying both 1.7.0 and 1.7.3). The GUI opens fine, but when I click on some of the options nothing happens, for example for database searching, denovo sequencing,  and one PSM no window pops up when I click on them. Other options are fine and function as expected, including spectrum library MS data. Is there a trick to getting the database search option to function?

**Comment by wenbostar** [comment]
What is the OS and the version of Java you are using?

**Comment by kbackus4** [comment]
Windows 10  (10.0.19042) and Java 8 v 291

**Comment by wenbostar** [comment]
Could you update your java to Java 10?

![image](https://user-images.githubusercontent.com/5302110/126186978-5d2982c0-1910-48bc-8c9d-f66557297ffa.png)


I use java 10 and it works well:

![image](https://user-images.githubusercontent.com/5302110/126186772-ff9c4ac2-5ee0-4860-a46f-f64e1b531474.png)

**Comment by kbackus4** [comment]
Thank you! That fixed the issue
