### ISSUE TITLE
No spectrum found despite correct scan title

### ISSUE THREAD

**Issue by asalt** [wenbostar/PDV#29]
Any idea why 1 spectrum fails to plot but the others do? Spectrum title is found in the mgf file

![Screenshot from 2021-12-02 13-05-56](https://user-images.githubusercontent.com/11843940/144486660-7ef140ee-d8f0-4000-871b-eb4531c1f483.png)

![Screenshot from 2021-12-02 13-08-30](https://user-images.githubusercontent.com/11843940/144487021-94c7251c-e40a-4159-9272-b150798fb825.png)

![Screenshot from 2021-12-02 13-06-55](https://user-images.githubusercontent.com/11843940/144486789-b2dbe163-b5d3-4894-8600-0c4c7201cfee.png)

**Comment by KaiLiCn** [comment]
Hi there,

Could you please share your data with us? I will take a look.

Kai

**Comment by wenbostar** [comment]
Hi Alex, I believe we could figure out the problem if you share your data to Kai.

**Comment by KaiLiCn** [comment]
Hi Alex, I think I found the problem. 
![image](https://user-images.githubusercontent.com/29800230/144733320-47656d81-c89f-415e-8edf-6c8a9aeb4f75.png)
In the TXT file you shared with me, I found one extra "space" character after this spectrum title. After deleting it, I can output this spectrum.

**Comment by wenbostar** [comment]
@KaiLiCn , you could add a step to remove any space in the start or the end of the string in a future version.

**Comment by asalt** [comment]
I see. I made that file manually and didn’t “see” that space. That’s what I get for editing manually. 

Thanks
Alex
