### ISSUE TITLE
Incompatible with Windows 11?

### ISSUE THREAD

**Issue by nova0613** [wenbostar/PDV#33]
After selecting the input files for database searching, the "loading data" bar pops up but the data never loads. I am running java 18.0.1.1 and PDV 1.7.4 with Windows 11. The same data loaded easily on a laptop running Windows 10. Is there any way around this? 

Thank you

**Comment by KaiLiCn** [comment]
Hi there,

Sorry for the issue. I think this is because of the Java version. Some of the libraries used in PDV don't support very new Java. Could you download an older version? <= 15 should be fine.

Kai

**Comment by nova0613** [comment]
Great! That worked. Thank you :)
