### ISSUE TITLE
PEAKS Studio Peptide Mapping issue

### ISSUE THREAD

**Issue by AtN01** [wenbostar/PDV#35]
Hi,

I am using PEAKS X plus Studio to process my raw data (that are TIC acquired with an LC-ESI-Q-Orbitrap). The software succeed in doing data refinement as well as the de novo sequencing, however when the software ends the processing the peptide mapping with the PTMs doesn't appear in the output.

Do you know what could be the cause of this issue ?

**Comment by wenbostar** [comment]
I think users should be able to get that information from the output tables. If you don't see that, you can ask PEAKS team for help.
