### ISSUE TITLE
Want to visualize results of XRNAX protocol

### ISSUE THREAD

**Issue by Arslan-Siraj** [wenbostar/PDV#37]
Hi!
Currently using Fragpipe to run XRNAX protocol, I have a couple of questions.

1. I run the XRNAX protocol, with results format of tsv_pepXML_pin. (Give me this error (Failed to parse result) in image)
<img width="1232" alt="Capture" src="https://user-images.githubusercontent.com/93129328/192835013-b67aefa9-151b-42ed-9eca-6c4d5b12b086.PNG">

2. What is right format to generate results?, I interested to visual spectra and see observed modification (ions with (RNA-adducts) mass adducts).

**Comment by KaiLiCn** [comment]
Hi,

Could you submit this issue under the FragPipe repository? Other members of the FragPipe team can also take a look.

Kai
