### ISSUE TITLE
Cannot navigate to subdirectory on MacOS

### ISSUE THREAD

**Issue by wsnoble** [wenbostar/PDV#39]
I am using the latest version of PDV on MacOS, and there seems to be a problem with the file selection dialog box.  When I want to open a file, the dialog box starts from my home directory, but I am unable to descend into any subdirectories.  I was forced to move the MGF file into my home directory in order to open it, but this seems like less-than-desirable behavior. :)

**Comment by wenbostar** [comment]
Hi Bill, this might be a java version issue. Could you tell me which version of java you're using?

**Comment by wsnoble** [comment]
% java --version
java --version
openjdk 11.0.15 2022-04-19
OpenJDK Runtime Environment (build 11.0.15+10)
OpenJDK 64-Bit Server VM (build 11.0.15+10, mixed mode)

**Comment by wenbostar** [comment]
It should work. How does the dialog box look like when it starts from your home directory?

For me, it looks like below and I can then go to any folder by double clicking the folder.

<img width="608" alt="image" src="https://user-images.githubusercontent.com/5302110/197352805-a9c41c91-fbcb-451c-82ea-870b35214a17.png">

**Comment by wsnoble** [comment]
Yes, that's what I saw.  When I tried it before, I got that screen, but no amount of double (or triple) clicking would let me enter any subdirectories. However, now I can't reproduce the problem, so I will close this issue. If it recurs, I will let you know.
