### ISSUE TITLE
Export picture from GUI

### ISSUE THREAD

**Issue by Kirovez** [wenbostar/PDV#4]
Export in ONE Psm mode does not work properly. In case of pdf it generates it but with loading bar in a top of the graph
[G_13_2.6100.6100.3 FileG_13_2.raw, NativeIDcontrollerType=0 controllerNumber=1 scan=6100.pdf](https://github.com/wenbostar/PDV/files/2339212/G_13_2.6100.6100.3.FileG_13_2.raw.NativeIDcontrollerType.0.controllerNumber.1.scan.6100.pdf)

PNG and TIFF files are not generated. Two files are generated: .temp and .png (or .tiff). While .tmp files contain something (they have certain weight), the .png and .tiff files are empty.

**Comment by wenbostar** [comment]
> Export in ONE Psm mode does not work properly. In case of pdf it generates it but with loading bar in a top of the graph

I think this may be caused by the big size of the figure. Can you make the figure size smaller? Please click the "**preview**" button after you change the size.

> PNG and TIFF files are not generated. Two files are generated: .temp and .png (or .tiff). While .tmp files contain something (they have certain weight), the .png and .tiff files are empty.

In this case, you can remove the file ".temp" and export figure again. It will solve the problem.

We will release a new version next week. We will not have these problems using the new version.

**Comment by Kirovez** [comment]
> I think this may be caused by the big size of the figure. Can you make the figure size smaller? Please click the "preview" button after you change the size.

OK, this helps, indeed.

> PNG and TIFF files are not generated. Two files are generated: .temp and .png (or .tiff). While .tmp files contain something (they have certain weight), the .png and .tiff files are empty.

This did not change something. I still have empty files. When I tried to delete them as well then I got message that the files are opened in Java.

**Comment by wenbostar** [comment]
Can you close PDV then try to delete the ".temp" file again?
