### ISSUE TITLE
Can't parse Tide file

### ISSUE THREAD

**Issue by wsnoble** [wenbostar/PDV#40]
The documentation says that the database search functionality can parse "MS-GF+, MyriMatch, X!Tandem, OMSSA (convert OMSSA raw result to mzIdentML format using MzidLib: https://github.com/PGB-LIV/mzidlib), Crux, Comet, Mascot, IPeak and
MSFragger."  Crux is the name of the toolkit, and it contains two search engines, Tide and Comet.  I tried to upload the attached Tide search results file, which ends in .txt.  When I do this, the dialog box allows me to specify one of three options: PDV format, MSAmanda and Philosopher.  How do I get it to read Tide format?  If I select PDV format, then it says the format is not supported.

[plasmo-neighbors.trypsin-p.narrow.tide-search.txt](https://github.com/wenbostar/PDV/files/9845386/plasmo-neighbors.trypsin-p.narrow.tide-search.txt)

**Comment by wenbostar** [comment]
For Crux/Tide, we currently support the following formats:

<img width="355" alt="image" src="https://user-images.githubusercontent.com/5302110/197365268-f4a3c3d1-991c-49a1-89c9-d32036967846.png">

We did the test on version 3.2. You can find examples at https://github.com/wenbostar/PDV/blob/master/README.md#database-searching.

**Comment by wenbostar** [comment]
For comet, we support the following output formats:
<img width="361" alt="image" src="https://user-images.githubusercontent.com/5302110/197365372-7ecd11f9-ad09-4787-b4d5-a8a3368b237e.png">

**Comment by wsnoble** [comment]
OK, sounds good. Maybe update the documentation to make this clearer?

**Comment by wenbostar** [comment]
Sorry for the confusion. I have updated the manual to make it clearer.
