### ISSUE TITLE
Issue with coloring of i* and r* ions.

### ISSUE THREAD

**Issue by freejstone** [wenbostar/PDV#43]
The following attached image shows iH ion colored green as if it was a matched b-ion. Peptide is QKNPSVIHF.

<img width="1433" alt="example" src="https://user-images.githubusercontent.com/74486962/198993043-d41ff3f7-9807-4fc4-a0db-4cb0f5904f92.png">

The mgf file containing the scan:

[MSB17171Chymotrypsin030814_5330.mgf.txt](https://github.com/wenbostar/PDV/files/9900488/MSB17171Chymotrypsin030814_5330.mgf.txt)

**Comment by wenbostar** [comment]
This is fixed in [v1.8.1](https://github.com/wenbostar/PDV/releases/tag/v1.8.1).

**Comment by wenbostar** [comment]
This issue has been fixed in [v1.8.1](https://github.com/wenbostar/PDV/releases/tag/v1.8.1). Could you please give the new version a try?

**Comment by freejstone** [comment]
Looks good to me. Thanks Bo!

<img width="1436" alt="Screen Shot 2023-05-27 at 11 18 02 am" src="https://github.com/wenbostar/PDV/assets/74486962/a3ba3c2a-5eb1-48be-9c97-ac8976f363a1">
