### ISSUE TITLE
Modifications ID'd by MetaMorpheus are not shown

### ISSUE THREAD

**Issue by Dmorgen** [wenbostar/PDV#5]
Hi,

I've imported a file searched by metamorpheus, and most scans containing various modifications are not shown. 
Additionally, when two peptides are identified from a single scan (mixed spectra), only one is shown in PDV. 

Thanks!
David.

**Comment by wenbostar** [comment]
Hi David,

> I've imported a file searched by metamorpheus, and most scans containing various modifications are not shown.

You're right, the current PSM table doesn't show the detailed modification information. We'll add a column to show that in the next version.

> Additionally, when two peptides are identified from a single scan (mixed spectra), only one is shown in PDV.

In default, PDV only imports the top 1 PSM for each spectrum in mzID file. If there are more than two PSMs for a spectrum in mzID file, only the peptide sequence from the top 2 PSM will be shown in the column "Other Assumption". If it's useful to import all ranks from the same spectrum and put them into separate rows, we can also do this in the next version. 

Bo

**Comment by Dmorgen** [comment]
thanks!

**Comment by wenbostar** [comment]
Modification information was added into the PSM table.
