### ISSUE TITLE
Grammar issues in manual

### ISSUE THREAD

**Issue by GrayGriffin** [wenbostar/PDV#6]
I have found several grammar issues while reading the PDV manual on your website. What is the best way for me to submit corrections for them?

**Comment by wenbostar** [comment]
Thank you very much. Could you tell me your email? I can send you a Word version for editing.

**Comment by GrayGriffin** [comment]
Sorry for the late reply. You can send it to doom.griffin@gmail.com. Should I send in the sections as I finish them individually?

**Comment by GrayGriffin** [comment]
Sorry for bumping this, but I haven't received a Word copy yet. I'm still available for editing, it's just that I've recently gotten a new work project so I might be slower.
