### ISSUE TITLE
Data loading issue

### ISSUE THREAD

**Issue by YechenHu** [wenbostar/PDV#66]
Hi，

I have been attempting to utilize PDV to visualize Glyco-peptide database search results, but I encountered an issue during the data upload step. The files I uploaded were in mzML and pepXML formats. Additionally, the software has been stuck in the 'uploading data' state for over two weeks, and I am unable to close it.

Thank you for your assistance.

![bug](https://github.com/wenbostar/PDV/assets/155591331/d780e12e-86cb-41bf-a24e-8abc590d5fd8)

**Comment by KaiLiCn** [comment]
Hi,

Sorry for the inconvenience.  Please open the` Task Manager`, select` PDV thread` and then `End` it.
![image](https://github.com/wenbostar/PDV/assets/29800230/57a5aee6-a72e-45a4-880c-45dbe261611f)

Now PDV only supports Glyco-peptide search results from FragPipe. Since the format changes in different version of FragPipe, I highly recommend you open the FP-PDV built inside the FragPipe after your search `Open FragPipe-PDV Viewer.` 
![image](https://github.com/wenbostar/PDV/assets/29800230/664a4a6f-a439-4673-ac4b-8d9d643e41fc)

Please let me know if you have difficulties opening your result inside FragPipe.

**Comment by YechenHu** [comment]
Thank you for your prompt response! It seems that FP-PDV defaults to opening the most recent search results. How can I open earlier search results from other dates?

**Comment by KaiLiCn** [comment]
You just need to copy your result folder path in `Output dir` or `Browse` it to set it.

**Comment by YechenHu** [comment]
Thanks. However, regardless of whether I use the browse or paste the path, I still encounter an error.
![Uploading Screenshot 2024-01-04 153406.png…]()

**Comment by KaiLiCn** [comment]
Sorry, I can't see your screenshot.

**Comment by YechenHu** [comment]
Sorry about that. The error is: Invalid spectrum file path, please check it.

**Comment by KaiLiCn** [comment]
1. Can you share your latest `.log` file with me?
2. Can you check the mzML file path in `*.manifest` file inside your result folder?

**Comment by YechenHu** [comment]
Please find my latest .log file and screenshot of my result folder.
[log_2023-12-15_10-58-48.txt](https://github.com/wenbostar/PDV/files/13835402/log_2023-12-15_10-58-48.txt)
![Screenshot 2024-01-04 result folder](https://github.com/wenbostar/PDV/assets/155591331/57d0423b-28dd-49fa-8233-1e013045805f)

**Comment by KaiLiCn** [comment]
Is it ok to share your whole folder with me? You could upload it here: https://www.dropbox.com/request/UISpGex3ISkS4muNPRLy 

I can take a quick test once I recieve it.

**Comment by YechenHu** [comment]
Thanks, I've uploaded it.

**Comment by KaiLiCn** [comment]
Based on the files you shared with me, I found the mzML file path is different with what you shown in your screenshot.
Here is the path in `fragpipe-files.fp-manifest` file.
![image](https://github.com/wenbostar/PDV/assets/29800230/58ffaa16-93ec-473c-8d87-65bdd310c6dd)
Here is your screenshot.
![image](https://github.com/wenbostar/PDV/assets/29800230/687410e9-416a-477d-95ee-7ea61ae2c0d7)

You probably moved your search result folder after your searching. Nothing wrong with your result. I can open it. You just need to change the mzML file path in the `fragpipe-files.fp-manifest` file, either absolute or reletive path with your result folder.
