### ISSUE TITLE
searching for scans across multiple pages

### ISSUE THREAD

**Issue by anesvi** [wenbostar/PDV#8]
I have a PSM.tsv file from FragPipe/philosopher and I can load it and mzML spectra. It works well.

However, as with any dataset, the data is split into multiple pages when I load it.

Is there a way to search for a particular peptide/protein/scan etc across ALL pages?
Sort the whole dataset?

It looks like those functionalities are applied to each page independently now. 

Thank you
Alexey Nesvizhskii

**Comment by wenbostar** [comment]
Hi Alexey, PDV already has these functions. Please take a look at page 3 of the [user's manual](http://pdv.zhang-lab.org/data/download/PDV-Manual.pdf).
