### ISSUE TITLE
Add a new modification

### ISSUE THREAD

**Issue by benqhan** [wenbostar/PDV#9]
Hi,
How can I define a new modification in PDV?

**Comment by wenbostar** [comment]
What is the format of your input?

**Comment by benqhan** [comment]
In "One PSM" visualization, I provided a MGF file and a peptide sequence as input. I know Modifications can be set by clicking the corresponding amino acid, but the modification is not in the list. I wonder if there is a way I can add the modification defined by formula in certain amino acid?

**Comment by wenbostar** [comment]
In this case, you can directly input the mass of the modification to the box like below:
![image](https://user-images.githubusercontent.com/5302110/60107255-3aa8b180-972c-11e9-97ee-4f8819e03647.png)

**Comment by benqhan** [comment]
It works well! Thanks a lot!

**Comment by wenbostar** [comment]
Great~
